#!/usr/bin/env bash
# init-autoresearch.sh — Initialize an autoresearch run
# Creates the output directory structure and baseline backup
set -euo pipefail

SKILL_PATH="${1:?Usage: init-autoresearch.sh <path-to-SKILL.md>}"
OUTPUT_DIR="${2:-}" # optional, defaults to autoresearch-{name}/ next to skill

if [[ ! -f "$SKILL_PATH" ]]; then
  echo "Error: SKILL.md not found at $SKILL_PATH" >&2
  exit 1
fi

SKILL_DIR="$(cd "$(dirname "$SKILL_PATH")" && pwd)"
SKILL_NAME="$(basename "$SKILL_DIR")"

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$HOME/.openclaw/workspace/autoresearch/$SKILL_NAME"
fi

mkdir -p "$OUTPUT_DIR"

# Backup original
if [[ -f "$OUTPUT_DIR/SKILL.md.baseline" ]]; then
  echo "Warning: baseline already exists at $OUTPUT_DIR/SKILL.md.baseline" >&2
  echo "  Skipping backup to preserve existing baseline." >&2
else
  cp "$SKILL_PATH" "$OUTPUT_DIR/SKILL.md.baseline"
  echo "Baseline saved: $OUTPUT_DIR/SKILL.md.baseline"
fi

# Initialize results.json
if [[ -f "$OUTPUT_DIR/results.json" ]]; then
  echo "Warning: results.json already exists. Not overwriting." >&2
else
  cat > "$OUTPUT_DIR/results.json" << EOF
{
  "skill_name": "$SKILL_NAME",
  "skill_path": "$SKILL_PATH",
  "status": "initialized",
  "config": {
    "evals_count": 0,
    "runs_per_experiment": 5,
    "budget_cap": null
  },
  "baseline": null,
  "best": null,
  "experiments": [],
  "eval_breakdown": []
}
EOF
  echo "Initialized: $OUTPUT_DIR/results.json"
fi

# Initialize changelog
if [[ ! -f "$OUTPUT_DIR/changelog.md" ]]; then
  cat > "$OUTPUT_DIR/changelog.md" << 'EOF'
# Autoresearch Changelog

Generated by autoresearch skill. Each experiment records the mutation, reasoning, and result.

EOF
  echo "Initialized: $OUTPUT_DIR/changelog.md"
fi

echo ""
echo "Autoresearch directory: $OUTPUT_DIR"
echo "Skill: $SKILL_NAME"
echo ""
echo "Next steps:"
echo "  1. Define 3-6 binary eval criteria"
echo "  2. Define 3-5 test inputs"
echo "  3. Run baseline (experiment #0)"
echo "  4. Start experiment loop"
